### ISSUE TITLE
Issue with cv2 import

### ISSUE THREAD

**Issue by emilyemchen** [yoterel/icatcher_plus#7]
Thanks for the great documentation! I'm having trouble running the Step 4 command, as I'm getting the following error: 

> traceback (most recent call last):
>   File "test.py", line 1, in <module>
>     import cv2
> ImportError: No module named cv2

This is the command I'm running (replacing the actual string to my directories with [PATHTO]): 

`python test.py [PATHTO]/icatcher_plus/models/icatcher+_lookit.pth --fc_model [PATHTO]/icatcher_plus/models/face_classifier_lookit_weights_best.pt --output_video_path [PATH TO ANNOTATED VIDEOS] --output_annotation [PATH TO ANNOTATIONS] --show_output`

My environment.yml file is up to date (e.g., using python 3.9).

I've tried `conda install opencv-python` and `conda install opencv`. Neither has worked. 

Any other suggestions that might help resolve this issue?

**Comment by yoterel** [comment]
Hi,
Can you try:
`pip install opencv-python`

Also, do you mind posting here the output when you do:
`conda list`

The reason is somehow cv2 was not installed in your case when you used the yml file, so I would like to investigate what went wrong. It indeed appears under the requirements and should have been installed (see [here](https://github.com/yoterel/icatcher_plus/blob/a52a3ecb5d02de94098f6c1a22d724885db66dcb/environment.yml#L20))

**Comment by emilyemchen** [comment]
Hi, 

Thanks for the quick reply! 

I should have mentioned that I tried `pip install opencv-python` and `brew install opencv-python` too. 

Here is the output from `pip install opencv-python`: 

> Requirement already satisfied: opencv-python in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (4.6.0.66)
> Requirement already satisfied: numpy>=1.19.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from opencv-python) (1.21.3)

Here is the output for `conda list`: 

> # packages in environment at miniconda3:
> #
> # Name                    Version                   Build  Channel
> brotlipy                  0.7.0           py39h1a28f6b_1002  
> ca-certificates           2022.07.19           hca03da5_0  
> certifi                   2022.6.15        py39hca03da5_0  
> cffi                      1.15.1           py39h22df2f2_0  
> charset-normalizer        2.0.4              pyhd3eb1b0_0  
> conda                     4.14.0           py39hca03da5_0  
> conda-package-handling    1.8.1            py39h1a28f6b_0  
> cryptography              37.0.1           py39h834c97f_0  
> cytoolz                   0.11.0           py39h1a28f6b_0  
> idna                      3.3                pyhd3eb1b0_0  
> libcxx                    14.0.6               h848a8c0_0  
> libffi                    3.4.2                hc377ac9_4  
> ncurses                   6.3                  h1a28f6b_3  
> openssl                   1.1.1q               h1a28f6b_0  
> pip                       22.1.2           py39hca03da5_0  
> pycosat                   0.6.3            py39h1a28f6b_0  
> pycparser                 2.21               pyhd3eb1b0_0  
> pyopenssl                 22.0.0             pyhd3eb1b0_0  
> pysocks                   1.7.1            py39hca03da5_0  
> python                    3.9.12               hbdb9e5c_0  
> python.app                3                py39h1a28f6b_0  
> readline                  8.1.2                h1a28f6b_1  
> requests                  2.28.1           py39hca03da5_0  
> ruamel_yaml               0.15.100         py39h1a28f6b_0  
> setuptools                63.4.1           py39hca03da5_0  
> sqlite                    3.39.2               h1058600_0  
> tk                        8.6.12               hb8d0fd4_0  
> toolz                     0.11.2             pyhd3eb1b0_0  
> tqdm                      4.64.0           py39hca03da5_0  
> tzdata                    2022a                hda174b7_0  
> urllib3                   1.26.11          py39hca03da5_0  
> wheel                     0.37.1             pyhd3eb1b0_0  
> xz                        5.2.5                h1a28f6b_1  
> yaml                      0.2.5                h1a28f6b_0  
> zlib                      1.2.12               h5a0b063_3

**Comment by yoterel** [comment]
Can you try to just:
`python -c "import cv2"`

does it throw any error?
is your conda environment active? (did you activate it ?)

**Comment by emilyemchen** [comment]
Yes, my conda environment is active. Just tried `python -c "import cv2"` and got this error: 

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ImportError: No module named cv2

**Comment by emilyemchen** [comment]
Also, I just tried commenting out the first line of "test.py" and then it had the same error for the next module the script is trying to import (PIL). So it might be an issue that is larger than just cv2.

**Comment by yoterel** [comment]
> Yes, my conda environment is active. Just tried python -c "import cv2" and got this error:

so it seems like the environment is not set up correctly, because even a plain python import doesn't work.

what does `python --version` output?

Also to be absolutely positive, can you print out what you get from:

`echo $CONDA_DEFAULT_ENV`
and 
`echo $CONDA_PREFIX`

do you get what you expect? (i.e. a path to the conda environment that you created)

**Comment by kolydic** [comment]
Hi @yoterel -- I am from the same lab as @emilyemchen. To make things simpler for ourselves, we produced a docker image of the icatcher_plus environment/dependencies  -- see my other issue here: #8 for more info. This works as a solution to @emilyemchen 's problems so this issue could be closed
