### ISSUE TITLE
conda environment alternative - docker container

### ISSUE THREAD

**Issue by kolydic** [yoterel/icatcher_plus#8]
Hello 

Just wanted to make a note that for our lab (Saxe lab, MIT) I created the required iCatcher working environment as a docker image that is available publicly here:  https://hub.docker.com/repository/docker/saxelab/looking_time_analysis

This docker image also contains a static copy of an icatcher_plus clone including the downloaded models. So, it can just be used as is. 

We download to our cluster to use as a singularity image like this:

`singularity singularity build --sandbox icatcher_env/ docker://saxelab/looking_time_analysis:icatcher_env ` 

make any required edits/updates (for us, currently none), then make immutable: 
`singularity build icatcher_env.sif icatcher_env/`

then run as: 
`singularity exec --cleanenv -B /filesystem_base:/filesystem_base icatcher_env.sif python3 /icatcher_plus/test.py $video_filepath /icatcher_plus/models/icatcher+_lookit.pth --fc_model /icatcher_plus/models/face_classifier_lookit.pth --output_annotation $project_path/data/icatcher_outputs --output_format compressed --output_video_path $project_path/data/icatcher_outputs`

**Comment by shariliu** [comment]
@yoterel I think that we should replace the current procedure for setting up the env for running icatcher, with this alternative method. Or at least, update the README to say that this is an option.

**Comment by yoterel** [comment]
@kolydic would you mind submitting a pull request that adds a section to the README.md file which clearly explains how to mount this docker image and make it work? (similar to your instructions here, but assume no prior knowledge) 

I have less experience with docker images, so this would be greatly appreciated !
